// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/[name].tsx";
import * as $3 from "./routes/chart/[name].ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Add.tsx";
import * as $$1 from "./islands/AndGate.tsx";
import * as $$2 from "./islands/NotGate.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/[name].tsx": $2,
    "./routes/chart/[name].ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Add.tsx": $$0,
    "./islands/AndGate.tsx": $$1,
    "./islands/NotGate.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
